name: CI

on:
  push:
    tags:
      - '**'
    branches:
      - main
  pull_request:
    branches:
      - main
      

jobs:
  config:
    if: github.ref != 'refs/tags/*'
    runs-on: ubuntu-latest
    outputs:
      trigger_type: ${{ steps.config.outputs.trigger_type }}
      version: ${{ steps.config.outputs.version }}
    steps:
      - name: Set trigger type and config
        id: config
        run: |
          echo "event: ${{ github.event_name }}, ref: ${{ github.ref }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "trigger_type=pull_request" >> $GITHUB_ENV
            echo "trigger_type=pull_request"
            echo "version=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
            echo "version=${{ github.event.pull_request.head.sha }}"V
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/heads/main ]]; then
            echo "trigger_type=main" >> $GITHUB_ENV
            echo "trigger_type=main"
            echo "version=${{ github.sha }}" >> $GITHUB_ENV
            echo "version=${{ github.sha }}"

          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/* ]]; then
            echo "trigger_type=tag" >> $GITHUB_ENV
            echo "trigger_type=tag"
            echo "version=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "version=${{ github.ref_name }}"
          else
            echo "Unknown trigger type"
            exit 1
          fi
