name: Create GH release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  create-github-release:
    name: Create GitHub Release 2 ${{ inputs.tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-depth: 0
          fetch-tags: true
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: build-package
          path: package
      - name: Get changelog
        run: awk '/^## / {s++} s == 1 {print}' CHANGELOG.md > release_notes.md
      - name: Create Github release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          generate_release_notes: false
          files: package/*
          tag_name: ${{ inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: release_notes.md
