name: Labels

on:
  pull_request:
    branches:
      - main
    types:
      - labeled

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:     
      - run: echo "executed $github.event.label.name"      

  deploy:
    if: github.event.label.name == 'upload'
    runs-on: ubuntu-latest
    steps:     
      - run: echo "executed"        
         
