name: Create a new version 

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-new-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
          fetch-tags: true

      - name: install
        run: yarn install --immutable

      - name: version bump
        run: |
          git config --global user.email "botexample.com"
          git config --global user.name "Mr. Bot"
          npm version ${{ inputs.version }}

      - name: Push
        run: git push origin main --tags
