name: Create a new version 

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-new-version:
    name: Update version
    permissions:
        contents: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-bump.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
          fetch-tags: true

      - name: install
        run: yarn install --immutable

      - name: version bump
        id: version-bump
        run: |
          git config --global user.email "botexample.com"
          git config --global user.name "Mr. Bot"
          VERSION=$(npm version ${{ inputs.version }})
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version: $VERSION" >> $GITHUB_STEP_SUMMARY

      - name: push tag
        run: git push origin main --tags

  release:
    name: Create GH release
    permissions:
        contents: write
    runs-on: ubuntu-latest
    needs: ['create-new-version']
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create-new-version.outputs.version }}
          release_name: Release ${{ needs.create-new-version.outputs.version }}
          body: |
            TBC
          draft: false
          prerelease: false
            
  deploy-to-dev:
    needs: ['create-new-version']
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy to dev
        run: echo Deployed to dev ${{ needs.create-new-version.outputs.version }}

  deploy-to-ops:
    needs: ['create-new-version']  
    runs-on: ubuntu-latest
    environment: ops
    steps:
      - name: deploy to ops
        run: echo Deployed to ops ${{ needs.create-new-version.outputs.version }}

  deploy-to-prod:
    needs: ['create-new-version']
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy to prod
        run: echo Deployed to prod ${{ needs.create-new-version.outputs.version }}


