name: Create a new version 

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-new-version:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
          fetch-tags: true

      - name: install
        run: yarn install --immutable

      - name: version bump
        run: |
          git config --global user.email "botexample.com"
          git config --global user.name "Mr. Bot"
          npm version ${{ inputs.version }}

      - name: push tag
        run: git push origin main --tags

      - name: Set version var
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        
  deploy-to-dev:
    needs: ['create-new-version']
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy to dev
        run: echo Deployed to dev ${GITHUB_REF##*/}

  deploy-to-ops:
    needs: ['create-new-version']  
    runs-on: ubuntu-latest
    environment: ops
    steps:
      - name: deploy to ops
        run: echo Deployed to ops ${{ github.ref_name }}

  deploy-to-prod:
    needs: ['create-new-version']
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy to prod
        run: echo Deployed to prod ${{ github.ref_name }}


