# This is a basic workflow to help you get started with Actions

name: Sha

on:
  push:
    branches: [ "main" ]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          sudo apt-get install jq
          sha=${{ github.sha }}
          hash=$(echo $sha | cut -c1-7)
          version=$(cat package.json | jq -r .version)
          echo v${{ version }}-${{ hash }}

          
