name: Upload

on:
  issue_comment:
    types: [ created ]

jobs:
  upload:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/upload')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
      - name: Debug
        run: |
          echo "Uploaded ${{ github.event.pull_request.head.sha }}"
